# Generated by Django 3.0.8 on 2020-07-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('imdbRating', models.PositiveIntegerField()),
                ('language', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
                ('summary', models.TextField()),
            ],
            options={
                'ordering': ['-imdbRating'],
            },
        ),
        migrations.CreateModel(
            name='MovieCastAward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cast', models.CharField(max_length=1000)),
                ('award', models.CharField(max_length=1000)),
                ('movie', models.ManyToManyField(to='recent_movies.Movie')),
            ],
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['name'], name='recent_movi_name_917d85_idx'),
        ),
    ]
