# Generated by Django 3.0.8 on 2020-07-23 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recent_movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviecastaward',
            name='movie',
        ),
        migrations.AddField(
            model_name='moviecastaward',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recent_movies.Movie'),
        ),
    ]
