# Generated by Django 3.0.8 on 2020-07-23 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recent_movies', '0003_auto_20200723_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviecastaward',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='castaward', to='recent_movies.Movie'),
        ),
    ]
